### ISSUE TITLE
[Discuss] Suggest better theme

### ISSUE THREAD

**Issue by Ashuto7h** [Dragsters/Nutrihelp#42]
### Describe the Issue
This issue contains only discussions about the theme and colors.
Suggest some better themes and colors, related to the category in which the app belongs. 

if you can work on Figma, you can copy our design and make changes to it.

**Comment by pratishthaa** [comment]
I can work on the design and make it more health-oriented, also I have experience in Graphic Designing. So, if needed, I can make changes there too.
Can I work on it?

**Comment by pratishthaa** [comment]
I added an image as background in add_patient_screen, but I get the error - unable to load asset.
Any suggestion?

**Comment by Ashuto7h** [comment]
Have you addressed the asset in pubspec. 
Create a draft pull request with latest code. 
Then only I can help

**Comment by pratishthaa** [comment]
Since the whole folder was added as an asset, so I didn't need to
and ok I will.

**Comment by pratishthaa** [comment]
![screenshot](https://user-images.githubusercontent.com/77200165/122217300-e83d9e00-ceca-11eb-8071-a691b1ad9634.png?width=100px&height=200px)
![screenshot](https://user-images.githubusercontent.com/77200165/122217341-f4296000-ceca-11eb-8fb0-9111741bae4e.png)
![screenshot](https://user-images.githubusercontent.com/77200165/122217363-f986aa80-ceca-11eb-9767-040da9da37a3.png)
![screenshot](https://user-images.githubusercontent.com/77200165/122217415-04d9d600-cecb-11eb-8767-6f019d6187c5.png)
![screenshot](https://user-images.githubusercontent.com/77200165/122217470-128f5b80-cecb-11eb-86f3-847aab253165.png)


These are the changes I have done so far.
So, instead of the gradient in add_patient, I wanted to add an image.
